### ISSUE TITLE
FastQC Failing

### ISSUE THREAD

**Issue by SophieS9** [guyleonard/evomics_2017#4]
AMI - Beta 1

FastQC running but failing (both using GUI and CLI).

Error messages from CLI:
```
genomics@ip-10-142-246-2:~/workshop_materials/quality_control$ fastqc bartonella_illumina.fastq 
java.io.FileNotFoundException: /etc/fastqc/Configuration/adapter_list.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at uk.ac.babraham.FastQC.Modules.AdapterContent.<init>(AdapterContent.java:75)
	at uk.ac.babraham.FastQC.Modules.ModuleFactory.getStandardModuleList(ModuleFactory.java:37)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.processFile(OfflineRunner.java:134)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.<init>(OfflineRunner.java:102)
	at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:316)
Started analysis of bartonella_illumina.fastq
java.io.FileNotFoundException: /etc/fastqc/Configuration/limits.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at uk.ac.babraham.FastQC.Modules.ModuleConfig.readParams(ModuleConfig.java:87)
	at uk.ac.babraham.FastQC.Modules.ModuleConfig.<clinit>(ModuleConfig.java:35)
	at uk.ac.babraham.FastQC.Modules.PerTileQualityScores.processSequence(PerTileQualityScores.java:174)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:88)
	at java.lang.Thread.run(Thread.java:745)
Approx 5% complete for bartonella_illumina.fastq
Approx 15% complete for bartonella_illumina.fastq
Approx 30% complete for bartonella_illumina.fastq
Approx 40% complete for bartonella_illumina.fastq
Approx 50% complete for bartonella_illumina.fastq
Approx 60% complete for bartonella_illumina.fastq
Approx 70% complete for bartonella_illumina.fastq
Approx 80% complete for bartonella_illumina.fastq
Approx 90% complete for bartonella_illumina.fastq
Approx 100% complete for bartonella_illumina.fastq
Analysis complete for bartonella_illumina.fastq
Failed to process file bartonella_illumina.fastq
java.lang.IllegalArgumentException: No key called gc_sequence:ignore in the config data
	at uk.ac.babraham.FastQC.Modules.ModuleConfig.getParam(ModuleConfig.java:148)
	at uk.ac.babraham.FastQC.Modules.PerSequenceGCContent.ignoreInReport(PerSequenceGCContent.java:57)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:331)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:155)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.lang.Thread.run(Thread.java:745)
genomics@ip-10-142-246-2:~/workshop_materials/quality_control$ 
```

Fresh download of the FastQC zip file, unzip, making fastqc executable and symbolic link to /usr/bin fixed it:
```
wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
cd FastQC 
chmod 755 fastqc 
sudo ln -s /home/master/FastQC/fastqc /usr/bin/
```

**Comment by guyleonard** [comment]
This is a bug in Ubuntu reported in 2015 [here](https://bugs.launchpad.net/ubuntu/+source/fastqc/+bug/1443275) - no idea why it isn't fixed. So I will remove fastqc from APT install and install manually.
